### PR TITLE
Snapcraft qxmledit

### PR DESCRIPTION
**Pull request by frederickjh**
This pull request adds the `snapcraft.yaml`  required to build the snap of QXmlEdit on [snapcraft.io](https://snapcraft.io).

### CODE REVIEW

**Comment by lbellonda** [comment]
Would you like to specify the license under which your file is released and put an header on it? Also do you mind to be cited between contributors by name or email?
I think to put the script under "install_script" folder.

**Comment by frederickjh** [comment]
@lbellonda The license would be the same as QXmlEdit's license. I have my repository licensed using the MIT license, but it that does not set the license on my pull request on your project. I do see that there is a configuration item to specify the license for the QXmlEdit project. I see three license files in QXmlEdit so I am not sure what I should add. See this page about [Snapcraft top-level metadata](https://docs.snapcraft.io/snapcraft-top-level-metadata/8334) to see the license codes that can be used. Let me know which ones I should add and I will add whatever is necessary and test.

Not sure what you mean by a header or why it would be added.
You can add me to the contributors list.

As to the location of the Snapcraft fille to build the Snap, build.snapcraft.io only allows snapcraft.yaml at /snap/snapcraft.yaml, /snapcraft.yaml or /.snapcraft.yaml. I used the recommended location and it builds correctly using this location. I would recommend using the current location, so that when the project decides to take over building the Snap itself the repository can be switched from [frederickjh/qxmledit](https://github.com/frederickjh/qxmledit) to this one.

**Comment by frederickjh** [comment]
Here is a [link](https://github.com/canonical-websites/build.snapcraft.io/issues/1094) to the information I could find about the location of the snapcraft.yaml file.

**Comment by frederickjh** [comment]
@lbellonda Thanks for accepting this pull request, and again let me know in the future if you and the other maintainers want to move the making of the snap package to this repository.

In any case until if you could send me a personal message when you make a new release, so I know that I need to rebuild the snap with the new version, I would appreciate it.

**Pull request merged**
